### ISSUE TITLE
minor/doc: suggest Flush after subscribe in examples/nats-sub.go

### ISSUE THREAD

**Issue by glycerine** [nats-io/nats#146]
Since Subscribe happens asynchronously, it would be kind to beginners to mention that nc.Flush() here is appropriate if you don't want to race waiting for your subscription taking effect.

https://github.com/nats-io/nats/blob/master/examples/nats-sub.go#L47

This caught me at first, resulting in racy tests that fortunately failed 20% of the time (if it had been 1% of the time, I'd have been very sad if I launched such code into production). The slack folks were helpful in sorting it out, but could have been avoided by having the example code do it and mention that it is optional if you want an async subscription (rare, but perf oriented).

**Comment by derekcollison** [comment]
All operations are ordered and consistent on a per connection basis. The fact that we optimize sending packets to the server should not be applicable unless you are doing multiple connections. But even then, one can reason that we can do Flush() or better yet make it synchronous. I use the Flush trick for multiple connection tests. However, as soon as the connections are connecting to separate servers (in a cluster) then Flush or a synchronous Subscribe does not guarantee ordering for a Subscribe on one and a Publish on another. Hopefully that makes sense.

**Comment by mcqueary** [comment]
Jason, I think more discussion of how connection flushing works is appropriate in the documentation, and we'll do that. Derek's right, though: nothing can guarantee the ordering of protocol messages between two different connections even if they are connected to the same server. The `nc.Flush()` happened to work in your case because of the specific timing, connecting to the same server, and who knows what else.  We will definitely enhance the documentation concerning the flushing behavior.
