### ISSUE TITLE
Please clearify fail-over behavior

### ISSUE THREAD

**Issue by phifty** [nats-io/nats#196]
I was wondering what exactly happens, if a client is connected to two nodes and one node fails? The docs describe the reconnect-logic, but I didn't found out what happens with the published messages while the node is re-connecting. I would expect that the messages are send to the remaining node, but is this correct? The code seems to buffer the messages for the later re-connect. I'll do further tests, but some clearification would be wonderful. Thanks in advance.

**Comment by kozlovic** [comment]
If by node you mean a NATS Server, then indeed, when a client gets disconnected from a server, and if configured to do so (URLs contain more than one server and options allow for reconnect), any publish or create of subscribers during the reconnect process are buffered and flushed once the reconnect succeeds.

Note that there is a default buffer size for published messages during a failover. Should the buffer fill-up, the publish call will fail. One can change the size of the reconnect buffer (`Options.ReconnectBufSize`).

**Comment by phifty** [comment]
Hmm... thanks for the information. Is there a way to make the client use the remaining working NATS server instead of buffering?

The background is that we have a couple of NATS servers on different machines and if one crashes at night, I would like that the traffic is routed through the other until the crashed one is repeared.

**Comment by kozlovic** [comment]
That's what's happening. The buffering only happens during the interval the client reconnects to the other server. Suppose you have 2 NATS Servers, let's call them A and B. You have a client configured with a list of servers A,B. Say the client initially connects to A. A crashes. The client initiates the reconnection logic to B. Depending on the `Options.ReconnectWait`, it is possible that the reconnect process takes few milliseconds or seconds. In *that* interval, if the client application still publishes messages, instead of simply losing them, they are buffered. Once the client connects to B, say after 1 second, during the reconnect handshake, buffered messages are flushed. Does that make sense?

**Comment by phifty** [comment]
That makes perfectly sense! Thanks for clearifying this.
