### ISSUE TITLE
auto discovery and multi datacenter useage

### ISSUE THREAD

**Issue by riaan53** [nats-io/nats#218]
Hi,

Thank you for nats! 

With the auto discovery thats been recently added how do I avoid my nats client in datacenter 1 to connect to the nats server in datacenter 2? For fallback it is awesome but under normal operation this would cause increased latency. Does the clients do perf/latency checking on the server routes to prioritize them?

Thanks!
Riaan

**Comment by kozlovic** [comment]
No perf/latency checking. As of know, urls in the list are randomly tried. The reconnect process stops when a connection is fully established.
That being said, could you describe to me how you are using (or would expect the things to work) without auto discovery? How are your clients configured at the moment?

**Comment by riaan53** [comment]
Thank you for the info.

On the clients im just using the server list that gets passed to `nats.Connect` atm with only the nats servers thats in the same location.

So if I use it like that and set the `nats.DontRandomize()` will all the auto-discovered nats servers be added to the end of the list and only be used if all the others fail?

All nats servers from all datacenters are in full mesh to provide global messaging/routing but we also have high performance local messaging/routing requirements for some location based gaming servers.

Thanks!

**Comment by kozlovic** [comment]
> So if I use it like that and set the nats.DontRandomize() will all the auto-discovered nats servers be added to the end of the list and only be used if all the others fail?

That's right. But, know this: when the client library gets disconnected, it picks the next server on the list by popping the current server, putting it at the end of the list, then selecting the head of list as long as number of reconnect attempts are under `MaxReconnect`.

To illustrate, say you have a mesh of 4 servers `A`,`B`,`C` and `D` with (`A`,`B`) in datacenter 1 and (`C`,`D`) in datacenter 2. Your application initially connects only with URLs for datacenter 1, that is `A`,`B`. On the initial connect to `A` (assuming the mesh is already fully formed), the client library will receive `B`,`C`,`D` (note, in no specific order here) and add to the end of the list `C` and `D` (since it already has `B`). 
So if randomization is disabled, if `A` goes down, your client will pop `A` from the list and add it to the end, and use `B`. Assume it connects OK, then great, you are still on datacenter 1. If `A` is restarted, and later `B` stops, the client will connect to the next in the list that may be `C` or `D` (again because we don't have a guarantee in the order of servers in the mesh received during connect), and `B` is put to the end of the list. So you are not really containing the client in datacenter 1 this way if the above occurs.

**Comment by riaan53** [comment]
Thank you for the detailed explenation! Looks like it will work nicely if I set the dont randomize and set up events to notify me when the client reconnects to other datacenter. Thanks again for the awesome work.
