### ISSUE TITLE
Order or lack thereof of callbacks

### ISSUE THREAD

**Issue by fraenkel** [nats-io/nats#30]
It seems a bit weird that in most cases I will see a ClosedCB and maybe a ReconnectedCB before the DisconnectedCB.  Because DCB is async, there is no order guarantee and it makes it difficult to actually do anything when you do see it since you cannot easily determine a reliable sequencing between the various callbacks.

**Comment by rbucker** [comment]
This might be a bad thing! Combining distributed state with concurrency and trying to implement some sort of event prioritization is probably not going to work. Instead you might want to use a callback controller instead of handler (same thing only validates local state against the event) and then decide what action is to be taken. Besides those callbacks are really for notification and if there was some action that needed to be executed... that would would be initiated in userspace anyway.

**Comment by fraenkel** [comment]
@rbucker Sure. Currently the callbacks aren't provided any details that would allow it to do anything sane. They are invoked and looking at the current state of the world is somewhat dangerous given no correlation key. The biggest issue is that the Disconnected CB for the previous connection can occur after the Reconnected CB. I don't know what safe actions you could take. If you knew that the Disconnected CB occurred for the previous aka different connection than the Reconnected then we are all good. I wasn't implying to get rid of the async nature although its a bit odd that only one of the have it.

**Comment by derekcollison** [comment]
I agree these should preserve order, and have a way to fix that on a per connection basis. I am not concerned regarding current state vs intended state when the event is processed. The event is to notify of a transition into a state, not the state itself, and the system could have transitioned out of said state before the notification is processed.
