### ISSUE TITLE
Callbacks are triggered when satisfied but not guaranteed to still be true

### ISSUE THREAD

**Issue by fraenkel** [nats-io/nats#38]
Both the reconnected and disconnected callbacks are invoked outside the Connection lock.  By doing so, the state of the connection may be different when actually invoked.  In most cases, the connection has been closed which leads to no harm.  However, in the case of the reconnect, another reconnect can occur since the socketwatchers have been spun up already.

**Comment by kozlovic** [comment]
Status callbacks are representing a state change, but do not guarantee that the state is still the same at the time the callback is invoked. We used to have calls to those callbacks either in place or in go routines, which could cause "out-of-order" callbacks. This has been addressed in #135. Closing this issue since there is no plan to guarantee connection status to not changed while callbacks are triggered.
