### ISSUE TITLE
ACK subscription hitting consumer too slow in pub-req

### ISSUE THREAD

**Issue by pkieltyka** [nats-io/nats#61]
Hello,

This is more of an FYI and follow up question, but I expect others will run into this as well.

The docs show an example like..

```go
// Requests
var response string
err := nc.Request("help", "help me", &response, 10*time.Millisecond)

// Replying
c.Subscribe("help", func(subj, reply string, msg string) {
    c.Publish(reply, "I can help!")
})
```

the request and reply use the same connection, which generally works fine. But in my stress tests the consumer wasn't firing fast enough, and the publish couldn't send anymore messages since "Slow Consumer Detected".

The solution was to have two separate connections to the nats server, one for the producers and one for the consumers. This solved my problem, but it makes me think if the nats client should be connection pooling?

**Comment by derekcollison** [comment]
You should not ever receive a slow consumer with request patterns since they wait for the response. Do you have a working example that you could send in a gist so that I can take a look?

**Comment by pkieltyka** [comment]
Hey @derekcollison - yea.. here it is: https://gist.github.com/pkieltyka/4de2d53d707e13014e4f

let me know if you have any suggestions. I am sending the PubReq asynchronously..

in this example I end up getting `2015/08/18 21:32:51 Err! write tcp [::1]:64236->[::1]:4222: write: broken pipe`  other times I was getting the slow consumer error

**Comment by derekcollison** [comment]
Yes if you are simply flooding publishes as fast as you can them you may
get a slow consumer. Best to possibly model by using a channel and a group
of workers who do straight nc.Request() to throttle properly.

**Comment by pkieltyka** [comment]
I see.. right now it's not a problem for us, even at our scale. I've just made a separate connection for now. It would be nice to buffer and somehow prevent the client from exploding though.

I'm just getting into nats, so I'm still learning the best way to crank out performance and build systems with it. So far I love it!

**Comment by derekcollison** [comment]
In a fire and forget system like NATS, unless you do ACKs / Requests, you
really don't know if you are over running the subscribers. You could
periodically do a Flush() call after N async requests.

**Comment by pkieltyka** [comment]
Hmm, how can we make this better though? I don't plan to use blocking Requests via `Request()`, and isn't a `PublishRequest()` is the same as a fire+forget packet but it includes a reply inbox payload for the consumer to pick up on and send something back? but for NATS to be what it has the potential to be, then IMO the producers / consumers need to be resilient to load out-of-the-box. 

I've been writing a library that wraps the nats go client to provide my services semi-guaranteed delivery in a pub-req+queue setup where each queue group is the name of the service to act on an event. The consumers on those services will need to reply to the inbox, which looks like `fmt.Sprintf("%s.%s", ackInboxForAll, requestID)` and the client has a simple ack inbox which parses out the requestID from the reply topic by listening on `#{ackInboxForAll}.>`. Etc.. I also want to add a middleware chain like with http handlers so I can let other apps inject across the request/response chain.

**Comment by derekcollison** [comment]
Peter,

If your program needs to know that something was received and processed,
then it should wait for the ACK. Also, request allows timeouts so that you
do not wait forever. Moreover, in Go, Goroutines are cheap and you can have
lots of them, so the blocking nature should not be of too much concern. In
your model, how do you know when one failed? What do you do when it does
fail?

In a real life scenario, you would scale the receivers up to a level to
support the publish load, usually as a queue group that can easily be
extended. I still would do a Request in a language like Go.

Also, as a last piece of information, messaging systems were publishing and
consuming are disconnected, you are always challenged with understanding
the deltas between the publishing rate and the consuming rate. I have
designed systems that tried to normalize that system wide, such that they
would slow publishers down if the consumer(s) could not keep up. NATS
specifically did not do this, but these flow patterns can be easily built
on top. The simplest is the Request/ACK pattern, but you can get more
sophisticated of course, even in your simple example, you know how many
requests are outstanding, if it gets too high, you can slow down the
publishing endpoints. Obviously you don't know this if the publisher and
receiver of the answer are not in the same process, but hopefully this
gives some insights into how to balance the deltas.

**Comment by pkieltyka** [comment]
Hi Derek,

Thanks for the insights, it definitely helps and makes me realize some flaws in my design.

My goal for a class of events is to ensure a message was consumed/processed successfully, and if it hadn't, then the publishers will persist that message and try again later. The flow is sending a request to a queue group and waiting for an ack. 

I've written a very basic version of that for my stack and it works. But there are things I've missed like flow rate throttling and message persistence for failed attempts.

Coordinating the distributed NATS servers will be tricky.. ie. where to persist failed messages for future retry? I would need a central or distributed data store for those messages to be retried, or just let the sender have a local store (but less fault-tolerant). Btw, I'm not suggesting NATS come with a distributed data store, but would be nice if it helped with the discovery/addressing part, in effect NATS could be the thing used to build a distributed data store (/end-tangent).

An example where guaranteed delivery helps is say a "user A follows user B". The event is fired by a frontend application (external stimuli), and it fires an event into the neuron network, different groups of the network will subscribe to the event "user.follows" and act on it. The goal is for each group to process the message, and if any group fails to do so, the message will be published to the failed groups again and again.

I'm thinking service design in the form of CSP over a network.. but is that over thinking it? .. I do think it would change how we design systems if it worked reliably and fast.

**Comment by derekcollison** [comment]
This is great feedback, and we have been thinking about how to enhance the
NATS ecosystem with this functionality. Stay tuned. NATS was designed to be
a fire and forget (nervous system like) messaging platform for always on
components. Asynch messaging and persistence for failures or disconnected
receivers is not part of core, but we are evaluating this as we extend
beyond the original design.

**Comment by pkieltyka** [comment]
awesome, I'm looking forward to hearing more and trying it out eventually!
