### ISSUE TITLE
Should we have a CONNECTING status?

### ISSUE THREAD

**Issue by kozlovic** [nats-io/nats#69]
When attempting to connect, the CONNECTED status is set early on. If for any reason during the connect and error is triggered (by processOpErr()), this may trigger a reconnect attempt, while we were in the middle of a connect. Maybe if we were using a CONNECTING status, we could use this in processOpErr() to simply return and not try to reconnect, since an error during connect() would correctly return the wrong status (and move on to the next on the server pool).

**Comment by derekcollison** [comment]
Is this applicable to auth in your opinion? In your opinion should we not try a reconnect?

**Comment by kozlovic** [comment]
I discovered this when testing if we were to get an error during the processConnectionInit. The call to Connect() will return an error anyway (so the user does not get a connection object), yet, the library is starting a reconnect process in the background. Even if that succeeds, the connection is useless since the user does not have a reference to it. It looks messy to me.

**Comment by derekcollison** [comment]
Ok good catch.. Thx






On Wed, Sep 9, 2015 at 8:03 PM -0700, "kozlovic" <notifications@github.com> wrote:










I discovered this when testing if we were to get an error during the processConnectionInit. The call to Connect() will return an error anyway (so the user does not get a connection object), yet, the library is starting a reconnect process in the background. Even if that succeeds, the connection is useless since the user does not have a reference to it. It looks messy to me.
